/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tugas_besar.view;

/**
 *
 * @author LENOVO
 */
public class PelayananView extends javax.swing.JPanel {

    /** Creates new form PelayananView */
    public PelayananView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        layanan = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        gtgChk = new javax.swing.JCheckBox();
        gcbChk = new javax.swing.JCheckBox();
        caviChk = new javax.swing.JCheckBox();
        smoothChk = new javax.swing.JCheckBox();
        rebonChk = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        chpChk = new javax.swing.JCheckBox();
        chwChk = new javax.swing.JCheckBox();
        tonChk = new javax.swing.JCheckBox();
        highChk = new javax.swing.JCheckBox();
        bleChk = new javax.swing.JCheckBox();
        facChk = new javax.swing.JCheckBox();
        alisChk = new javax.swing.JCheckBox();
        tertelChk = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        fajeChk = new javax.swing.JCheckBox();
        fawhiChk = new javax.swing.JCheckBox();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnTotal = new javax.swing.JToggleButton();
        jLabel = new javax.swing.JLabel();

        layanan.setBackground(new java.awt.Color(255, 102, 255));
        layanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("LAYANAN SALON");
        layanan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 22, 390, 30));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Gunting Wanita");
        layanan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        layanan.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 85, 10));

        gtgChk.setBackground(new java.awt.Color(255, 255, 255));
        gtgChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        gtgChk.setForeground(new java.awt.Color(0, 0, 0));
        gtgChk.setText("Gunting");
        gtgChk.setBorder(null);
        gtgChk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        layanan.add(gtgChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 106, -1, -1));

        gcbChk.setBackground(new java.awt.Color(255, 255, 255));
        gcbChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        gcbChk.setForeground(new java.awt.Color(0, 0, 0));
        gcbChk.setText("Gunting + Cuci + Blow");
        gcbChk.setBorder(null);
        layanan.add(gcbChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, 23));

        caviChk.setBackground(new java.awt.Color(255, 255, 255));
        caviChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        caviChk.setForeground(new java.awt.Color(0, 0, 0));
        caviChk.setText("Catok + Vitamin");
        caviChk.setBorder(null);
        layanan.add(caviChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 169, -1, -1));

        smoothChk.setBackground(new java.awt.Color(255, 255, 255));
        smoothChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        smoothChk.setForeground(new java.awt.Color(0, 0, 0));
        smoothChk.setText("Smoothing");
        smoothChk.setBorder(null);
        layanan.add(smoothChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 196, -1, -1));

        rebonChk.setBackground(new java.awt.Color(255, 255, 255));
        rebonChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        rebonChk.setForeground(new java.awt.Color(0, 0, 0));
        rebonChk.setText("Rebonding");
        rebonChk.setBorder(null);
        layanan.add(rebonChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 223, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Harga");
        layanan.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 70, 39, -1));
        layanan.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 90, 39, 10));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("10.000");
        layanan.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 106, -1, -1));

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("20.000");
        layanan.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 136, -1, -1));

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("20.000");
        layanan.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 167, -1, -1));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("175.000");
        layanan.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 194, -1, -1));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("75.000");
        layanan.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 221, -1, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Colouring");
        layanan.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 70, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Harga");
        layanan.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 70, -1, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Perawatan Wajah");
        layanan.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 70, -1, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Harga");
        layanan.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 70, -1, -1));
        layanan.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 90, 54, 10));
        layanan.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 33, 10));
        layanan.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 90, 92, 10));
        layanan.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 90, 32, 10));

        chpChk.setBackground(new java.awt.Color(255, 255, 255));
        chpChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        chpChk.setForeground(new java.awt.Color(0, 0, 0));
        chpChk.setText("Cat Hitam Pria");
        chpChk.setBorder(null);
        chpChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpChkActionPerformed(evt);
            }
        });
        layanan.add(chpChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 108, -1, -1));

        chwChk.setBackground(new java.awt.Color(255, 255, 255));
        chwChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        chwChk.setForeground(new java.awt.Color(0, 0, 0));
        chwChk.setText("Cat Hitam Wanita");
        chwChk.setBorder(null);
        layanan.add(chwChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 138, -1, -1));

        tonChk.setBackground(new java.awt.Color(255, 255, 255));
        tonChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tonChk.setForeground(new java.awt.Color(0, 0, 0));
        tonChk.setText("Toning");
        tonChk.setBorder(null);
        layanan.add(tonChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 167, -1, -1));

        highChk.setBackground(new java.awt.Color(255, 255, 255));
        highChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        highChk.setForeground(new java.awt.Color(0, 0, 0));
        highChk.setText("Highlight");
        highChk.setBorder(null);
        layanan.add(highChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 196, -1, -1));

        bleChk.setBackground(new java.awt.Color(255, 255, 255));
        bleChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        bleChk.setForeground(new java.awt.Color(0, 0, 0));
        bleChk.setText("Bleaching");
        bleChk.setBorder(null);
        layanan.add(bleChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 223, -1, -1));

        facChk.setBackground(new java.awt.Color(255, 255, 255));
        facChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        facChk.setForeground(new java.awt.Color(0, 0, 0));
        facChk.setText("Facial");
        facChk.setBorder(null);
        layanan.add(facChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 108, -1, -1));

        alisChk.setBackground(new java.awt.Color(255, 255, 255));
        alisChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        alisChk.setForeground(new java.awt.Color(0, 0, 0));
        alisChk.setText("Merapikan Alis");
        alisChk.setBorder(null);
        alisChk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alisChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisChkActionPerformed(evt);
            }
        });
        layanan.add(alisChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 138, -1, -1));

        tertelChk.setBackground(new java.awt.Color(255, 255, 255));
        tertelChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tertelChk.setForeground(new java.awt.Color(0, 0, 0));
        tertelChk.setText("Terapi Telinga");
        tertelChk.setBorder(null);
        layanan.add(tertelChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 169, -1, -1));

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("35.000");
        layanan.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 106, -1, -1));

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("50.000");
        layanan.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 133, -1, -1));

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("35.000");
        layanan.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 167, -1, -1));

        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("50.000");
        layanan.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 194, -1, -1));

        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("35.000");
        layanan.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 221, -1, -1));

        fajeChk.setBackground(new java.awt.Color(255, 255, 255));
        fajeChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        fajeChk.setForeground(new java.awt.Color(0, 0, 0));
        fajeChk.setText("Facial Jerawat");
        fajeChk.setBorder(null);
        layanan.add(fajeChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 196, -1, -1));

        fawhiChk.setBackground(new java.awt.Color(255, 255, 255));
        fawhiChk.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        fawhiChk.setForeground(new java.awt.Color(0, 0, 0));
        fawhiChk.setText("Facial Whitening");
        fawhiChk.setBorder(null);
        layanan.add(fawhiChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("30.000");
        layanan.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 106, -1, -1));

        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("5.000");
        layanan.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 136, -1, -1));

        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("25.000");
        layanan.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 167, -1, -1));

        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("55.000");
        layanan.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 194, -1, -1));

        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("75.000");
        layanan.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 221, -1, -1));

        txtArea.setBackground(new java.awt.Color(255, 255, 255));
        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setBorder(null);
        jScrollPane3.setViewportView(txtArea);

        layanan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 500, 100));

        btnTotal.setBackground(new java.awt.Color(204, 204, 204));
        btnTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(0, 0, 0));
        btnTotal.setText("TOTAL");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        layanan.add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setIcon(new javax.swing.ImageIcon("D:\\Icon\\ew.jpg")); // NOI18N
        layanan.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 610, 630));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alisChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisChkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alisChkActionPerformed

    private void chpChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpChkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chpChkActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        double total = 0;
        
        if (gtgChk.isSelected()){
            total = total + 10000;
        } if (gcbChk.isSelected()){
            total = total + 20000;
        } if (caviChk.isSelected()){
            total = total + 20000;
        } if (smoothChk.isSelected()){
            total = total + 175000;
        } if (rebonChk.isSelected()){
            total = total + 75000;
        } if (chpChk.isSelected()){
            total = total + 35000;
        } if (chwChk.isSelected()){
            total = total + 50000;
        } if (tonChk.isSelected()){
            total = total + 35000;
        } if (highChk.isSelected()){
            total = total + 50000;
        } if (bleChk.isSelected()){
            total = total + 35000;
        } if (facChk.isSelected()){
            total = total + 30000;
        } if (alisChk.isSelected()){
            total = total + 5000;
        } if (tertelChk.isSelected()){
            total = total + 25000;
        } if (fajeChk.isSelected()){
            total = total + 55000;
        } if (fawhiChk.isSelected()){
            total = total + 75000;
        }
        
        txtArea.setText(Double.toString(total));
        
        total = Double.parseDouble(txtArea.getText());
        
        txtArea.setText("Total harga dari pilihan layanan adalah RP."+total);
    }//GEN-LAST:event_btnTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alisChk;
    private javax.swing.JCheckBox bleChk;
    private javax.swing.JToggleButton btnTotal;
    private javax.swing.JCheckBox caviChk;
    private javax.swing.JCheckBox chpChk;
    private javax.swing.JCheckBox chwChk;
    private javax.swing.JCheckBox facChk;
    private javax.swing.JCheckBox fajeChk;
    private javax.swing.JCheckBox fawhiChk;
    private javax.swing.JCheckBox gcbChk;
    private javax.swing.JCheckBox gtgChk;
    private javax.swing.JCheckBox highChk;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel layanan;
    private javax.swing.JCheckBox rebonChk;
    private javax.swing.JCheckBox smoothChk;
    private javax.swing.JCheckBox tertelChk;
    private javax.swing.JCheckBox tonChk;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

}
