/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kelompok8.view;

/**
 *
 * @author Acer
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registrasi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNama1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        btnRegistrasi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(232, 61, 141));
        login.setMinimumSize(new java.awt.Dimension(700, 460));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 170, 60));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setText("USERNAME");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, 40));

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(232, 61, 141));
        txtNama.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        txtNama.setText("Masukkan username anda");
        txtNama.setBorder(null);
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
        });
        login.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, 20));
        login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/user.png"))); // NOI18N
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 40, 40));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setText("PASSWORD");
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 140, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/Password.png"))); // NOI18N
        login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, 40));
        login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 230, 10));

        txtPass.setBackground(new java.awt.Color(232, 61, 141));
        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
        });
        login.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 230, 20));

        btnLogin.setBackground(new java.awt.Color(232, 61, 141));
        btnLogin.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        btnLogin.setText("LOGIN");
        login.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/Salon Background.png"))); // NOI18N
        login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 300));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        jLabel2.setText("Gapunya akun? Register disini");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 160, -1));

        bgPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        registrasi.setBackground(new java.awt.Color(232, 61, 141));
        registrasi.setMinimumSize(new java.awt.Dimension(700, 460));
        registrasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel9.setText("REGISTRASI");
        registrasi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 290, 60));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel10.setText("NAME");
        registrasi.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 140, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/user.png"))); // NOI18N
        registrasi.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, 40));

        txtNama1.setEditable(false);
        txtNama1.setBackground(new java.awt.Color(232, 61, 141));
        txtNama1.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        txtNama1.setText("Masukkan nama anda");
        txtNama1.setBorder(null);
        txtNama1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNama1FocusGained(evt);
            }
        });
        registrasi.add(txtNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 20));
        registrasi.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, 10));

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel20.setText("USERNAME");
        registrasi.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 140, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/user.png"))); // NOI18N
        registrasi.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 40, 40));

        txtUsername.setEditable(false);
        txtUsername.setBackground(new java.awt.Color(232, 61, 141));
        txtUsername.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        txtUsername.setText("Masukkan username anda");
        txtUsername.setBorder(null);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
        });
        registrasi.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 20));
        registrasi.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 230, 10));

        jLabel24.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel24.setText("E-MAIL");
        registrasi.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/user.png"))); // NOI18N
        registrasi.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 40, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(232, 61, 141));
        txtEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        txtEmail.setText("Masukkan e-mail anda");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        registrasi.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 230, -1));
        registrasi.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 230, -1));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel12.setText("PASSWORD");
        registrasi.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 140, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/Password.png"))); // NOI18N
        registrasi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, 40));

        txtPass1.setBackground(new java.awt.Color(232, 61, 141));
        txtPass1.setText("jPasswordField1");
        txtPass1.setBorder(null);
        txtPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass1FocusGained(evt);
            }
        });
        registrasi.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 230, 20));
        registrasi.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 230, 10));

        btnRegistrasi.setBackground(new java.awt.Color(232, 61, 141));
        btnRegistrasi.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        btnRegistrasi.setText("REGISTRASI");
        registrasi.add(btnRegistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 230, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/kelompok8/images/Salon Background.png"))); // NOI18N
        registrasi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bgPanel.add(registrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        // TODO add your handling code here:
        txtNama.setText("");
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
        txtPass.setText("");
    }//GEN-LAST:event_txtPassFocusGained

    private void txtNama1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNama1FocusGained
        // TODO add your handling code here:
        txtNama1.setText("");
    }//GEN-LAST:event_txtNama1FocusGained

    private void txtPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1FocusGained

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new View().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel login;
    private javax.swing.JPanel registrasi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
