/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tugas_besar.view;

/**
 *
 * @author LENOVO
 */
public class PelayananView extends javax.swing.JPanel {

    /** Creates new form PelayananView */
    public PelayananView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        layanan = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnTotal = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        layanan.setBackground(new java.awt.Color(255, 102, 255));
        layanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("LAYANAN SALON");
        layanan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 22, 390, 30));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Gunting Wanita");
        layanan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        layanan.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 85, 10));

        jCheckBox17.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox17.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox17.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox17.setText("Gunting");
        jCheckBox17.setBorder(null);
        jCheckBox17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        layanan.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 106, -1, -1));

        jCheckBox18.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox18.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox18.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox18.setText("Gunting + Cuci + Blow");
        jCheckBox18.setBorder(null);
        layanan.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, -1, 23));

        jCheckBox19.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox19.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox19.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox19.setText("Catok + Vitamin");
        jCheckBox19.setBorder(null);
        layanan.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 169, -1, -1));

        jCheckBox20.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox20.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox20.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox20.setText("Smoothing");
        jCheckBox20.setBorder(null);
        layanan.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 196, -1, -1));

        jCheckBox21.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox21.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox21.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox21.setText("Rebonding");
        jCheckBox21.setBorder(null);
        layanan.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 223, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Harga");
        layanan.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 70, 39, -1));
        layanan.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 90, 39, 10));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("10.000");
        layanan.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 106, -1, -1));

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("20.000");
        layanan.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 136, -1, -1));

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("20.000");
        layanan.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 167, -1, -1));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("175.000");
        layanan.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 194, -1, -1));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("75.000");
        layanan.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 221, -1, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Colouring");
        layanan.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 70, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Harga");
        layanan.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 70, -1, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Perawatan Wajah");
        layanan.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 70, -1, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Harga");
        layanan.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 70, -1, -1));
        layanan.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 90, 54, 10));
        layanan.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 33, 10));
        layanan.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 90, 92, 10));
        layanan.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 90, 32, 10));

        jCheckBox22.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox22.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox22.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox22.setText("Cat Hitam Pria");
        jCheckBox22.setBorder(null);
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        layanan.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 108, -1, -1));

        jCheckBox23.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox23.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox23.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox23.setText("Cat Hitam Wanita");
        jCheckBox23.setBorder(null);
        layanan.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 138, -1, -1));

        jCheckBox24.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox24.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox24.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox24.setText("Toning");
        jCheckBox24.setBorder(null);
        layanan.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 167, -1, -1));

        jCheckBox25.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox25.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox25.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox25.setText("Highlight");
        jCheckBox25.setBorder(null);
        layanan.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 196, -1, -1));

        jCheckBox26.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox26.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox26.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox26.setText("Bleaching");
        jCheckBox26.setBorder(null);
        layanan.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 223, -1, -1));

        jCheckBox27.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox27.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox27.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox27.setText("Facial");
        jCheckBox27.setBorder(null);
        layanan.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 108, -1, -1));

        jCheckBox28.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox28.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox28.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox28.setText("Merapikan Alis");
        jCheckBox28.setBorder(null);
        jCheckBox28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
            }
        });
        layanan.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 138, -1, -1));

        jCheckBox29.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox29.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox29.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox29.setText("Terapi Telinga");
        jCheckBox29.setBorder(null);
        layanan.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 169, -1, -1));

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("35.000");
        layanan.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 106, -1, -1));

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("50.000");
        layanan.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 133, -1, -1));

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("35.000");
        layanan.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 167, -1, -1));

        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("50.000");
        layanan.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 194, -1, -1));

        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("35.000");
        layanan.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 221, -1, -1));

        jCheckBox30.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox30.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox30.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox30.setText("Facial Jerawat");
        jCheckBox30.setBorder(null);
        layanan.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 196, -1, -1));

        jCheckBox31.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox31.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jCheckBox31.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox31.setText("Facial Whitening");
        jCheckBox31.setBorder(null);
        layanan.add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 223, -1, -1));

        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("30.000");
        layanan.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 106, -1, -1));

        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("5.000");
        layanan.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 136, -1, -1));

        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("25.000");
        layanan.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 167, -1, -1));

        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("55.000");
        layanan.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 194, -1, -1));

        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("75.000");
        layanan.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 221, -1, -1));

        txtArea.setBackground(new java.awt.Color(204, 204, 204));
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane3.setViewportView(txtArea);

        layanan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 316, 143));

        btnTotal.setBackground(new java.awt.Color(204, 204, 204));
        btnTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(0, 0, 0));
        btnTotal.setText("TOTAL");
        layanan.add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Icon\\ew.jpg")); // NOI18N
        layanan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 610, 630));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox28ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnTotal;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel layanan;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

}
